"""add landing services and contacts

Revision ID: d985a1aaeeb8
Revises: 67be4e9e23b2
Create Date: 2026-02-21 10:35:14.017582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd985a1aaeeb8'
down_revision = '67be4e9e23b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['landing_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landing_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['landing_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landing_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_request', schema=None) as batch_op:
        batch_op.drop_column('qr_code')

    op.drop_table('landing_service')
    op.drop_table('contact')
    # ### end Alembic commands ###
