"""add landing_request table

Revision ID: e94e9d960833
Revises: 5b1f857d75f0
Create Date: 2026-02-17 18:54:38.415723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94e9d960833'
down_revision = '5b1f857d75f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=20), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('generated_prompt', sa.Text(), nullable=True),
    sa.Column('generated_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landing_request')
    # ### end Alembic commands ###
