"""add landing_type and b2b contact fields

Revision ID: f60373e35def
Revises: e94e9d960833
Create Date: 2026-02-18 11:38:39.419161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60373e35def'
down_revision = 'e94e9d960833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landing_type', sa.String(length=3), nullable=False, server_default='b2c'))
        batch_op.add_column(sa.Column('contact_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_request', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('landing_type')

    # ### end Alembic commands ###
